routes/web.php
<?php

use App\Http\Controllers\AutoController;
use App\Http\Controllers\BonusController;
use App\Http\Controllers\CertificateController;
use App\Http\Controllers\ConcernController;
use App\Http\Controllers\ConclusionController;
use App\Http\Controllers\DebitController;
use App\Http\Controllers\DillerController;
use App\Http\Controllers\DistrictController;
use App\Http\Controllers\EstateController;
use App\Http\Controllers\FileStoreController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\NotificationTemplateController;
use App\Http\Controllers\NotificationTypeController;
use App\Http\Controllers\OrderMembersController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\PurposeController;
use App\Http\Controllers\QrController;
use App\Http\Controllers\RegionController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\ToolsController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\UserInfoController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
//Language Translation
Route::get('index/{locale}', [HomeController::class, 'lang']);

Route::get('/', [HomeController::class, 'index'])->name('root');
Route::get('index', [HomeController::class, 'index'])->name('index');

//Update User Details
Route::post('/update-profile/{id}', [ProfileController::class, 'updateProfile'])->name('updateProfile');
Route::post('/update-password/{id}', [ProfileController::class, 'updatePassword'])->name('updatePassword');
Route::get('qr/show/{content}', [QrController::class, 'show'])->name('qr.show');
Route::get('qr/re-generate/{id}/{type}', [QrController::class, 'reGenerate'])->name('qr.generate');
Route::get('conclusion/test-water-mark', [ConclusionController::class, 'testWaterMark'])->name('wm.show');

Route::post('/member/remove', [OrderMembersController::class, 'remove'])->name('member.remove');
Route::post('/members/invite', [OrderMembersController::class, 'invite'])->name('members.invite');

Route::get('/estate', [EstateController::class, 'index'])->name('estate.index');
Route::get('/estate/create', [EstateController::class, 'create'])->name('estate.create');
Route::post('/estate/store', [EstateController::class, 'store'])->name('estate.store');
Route::get('/estate/edit/{id}', [EstateController::class, 'edit'])->name('estate.edit');
Route::put('/estate/update/{id}', [EstateController::class, 'update'])->name('estate.update');
Route::get('/estate/show/{order}', [EstateController::class, 'show'])->name('estate.show');
Route::get('/estate/show-activities/{order}', [EstateController::class, 'showActivities'])->name('estate.show-activities');
Route::get('/estate/show-team/{order}', [EstateController::class, 'showTeam'])->name('estate.show-team');
Route::get('/estate/show-documents/{order}', [EstateController::class, 'showDocuments'])->name('estate.show-documents');
Route::put('/estate/order-clone/{id}', [EstateController::class, 'orderClone'])->name('estate.clone');

Route::get('/auto', [AutoController::class, 'index'])->name('auto.index');
Route::get('/auto/create', [AutoController::class, 'create'])->name('auto.create');
Route::post('/auto/store', [AutoController::class, 'store'])->name('auto.store');
Route::get('/auto/edit/{id}', [AutoController::class, 'edit'])->name('auto.edit');
Route::put('/auto/update/{id}', [AutoController::class, 'update'])->name('auto.update');
Route::get('/auto/show/{order}', [AutoController::class, 'show'])->name('auto.show');
Route::get('/auto/show-activities/{order}', [AutoController::class, 'showActivities'])->name('auto.show-activities');
Route::get('/auto/show-team/{order}', [AutoController::class, 'showTeam'])->name('auto.show-team');
Route::get('/auto/show-documents/{order}', [AutoController::class, 'showDocuments'])->name('auto.show-documents');
Route::put('/auto/order-clone/{id}', [AutoController::class, 'orderClone'])->name('auto.clone');

Route::get('/conclusion/add/{id}/{type}', [ConclusionController::class, 'create'])->name('conclusion.add');
Route::post('/conclusion/store', [ConclusionController::class, 'store'])->name('conclusion.store');
Route::put('/conclusion/reject', [ConclusionController::class, 'reject'])->name('conclusion.reject');


Route::get('/tools', [ToolsController::class, 'index'])->name('tools.index');
Route::get('/user', [UserController::class, 'index'])->name('user.index');
Route::post('/user/store', [UserController::class, 'create'])->name('user.store');
Route::get('/user/show/{id}', [UserController::class, 'show'])->name('user.show');
Route::put('/user/update', [UserController::class, 'update'])->name('user.update');
Route::post('/user/favourite/{id}', [UserController::class, 'favourite'])->name('user.favourite');
Route::put('/user/password/change', [UserController::class, 'updatePassword'])->name('password.change');

Route::get('/user/info/edit', [UserInfoController::class, 'edit'])->name('profile.info.edit');
Route::put('/user/info/store', [UserInfoController::class, 'update'])->name('profile.info.update');

Route::get('/profile/edit', [UserController::class, 'edit'])->name('profile.edit');
Route::put('/profile/update', [UserController::class, 'update'])->name('profile.update');
Route::get('/profile/show-activities', [ProfileController::class, 'showActivities'])->name('profile.show-activities');
Route::get('/profile/show-projects', [ProfileController::class, 'showProjects'])->name('profile.show-projects');
Route::get('/profile/show-documents', [ProfileController::class, 'showDocuments'])->name('profile.show-documents');

Route::get('/user/profile', [ProfileController::class, 'profile'], 'profile')->name('profile');
Route::put('/user/activate/{id}', [UserController::class, 'activate'])->name('user.activate');
Route::put('/user/block/{id}', [UserController::class, 'block'])->name('user.block');
Route::get('/user/appraisers', [UserController::class, 'appraisers'])->name('user.appraisers');
Route::get('/appraisers/bonus', [UserController::class, 'appraisersBonus'])->name('appraisers.bonus');
Route::delete('/diller/{id}', [UserController::class, 'destroy'])->name('diller.destroy');

Route::get('/diller', DillerController::class)->name('diller.index');
Route::get('/role', [RoleController::class, 'index'])->name('role.index');
Route::put('/role/permit', [RoleController::class, 'permit'])->name('role.permit');
Route::get('/notification/type', NotificationTypeController::class)->name('notification.type.index');
Route::get('/notification/template', [NotificationTemplateController::class, 'index'])->name('notification.template.index');
//Route::post('/store/my/file', [FileStoreController::class, 'storeMyFile'])->name('store.my.file');
Route::post('/attach/file', [FileStoreController::class, 'attachFiles'])->name('attach.files');
Route::post('/attach/profile-file', [FileStoreController::class, 'attachProfileFiles'])->name('profile.files');
Route::get('/download/{file}', [FileStoreController::class, 'downloadFile'])->name('download');
Route::delete('file/delete/{file}', [FileStoreController::class, 'delete'])->name('file.delete');
Route::put('debit/credit', [BonusController::class, 'storeCredit'])->name('credit.store');
Route::resource('/debit', DebitController::class);
Route::resource('bonus', BonusController::class);
Route::resource('certificates', CertificateController::class);
Route::resource('purposes', PurposeController::class);
Route::resource('regions', RegionController::class);
Route::get('/regions/districts/{id}', [RegionController::class, 'districts'])->name('regions.districts');
Route::resource('districts', DistrictController::class);
Route::resource('concerns', ConcernController::class);

Route::get('{any}', [HomeController::class, 'pages'])->name('pages');

app/Models/Region.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Region extends Model
{
    use HasFactory;


    protected $fillable = [
        'uz',
        'ru',
        'cr'
    ];
}

app/Http/Controllers/RegionController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreRegionRequest;
use App\Http\Requests\UpdateRegionRequest;
use App\Models\District;
use App\Models\Region;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Support\Facades\Redirect;

class RegionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View
     */
    public function index(): Application|Factory|View
    {
        return view("regions.index", [
            'regions' => Region::all()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|View
     */
    public function create(): Application|Factory|View
    {
        return view("regions.create");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param StoreRegionRequest $request
     * @return RedirectResponse
     */
    public function store(StoreRegionRequest $request): RedirectResponse
    {
        Region::create($request->validated());
        return Redirect::to('regions');
    }

    /**
     * Display the specified resource.
     *
     * @param Region $region
     * @return Application|Factory|View
     */
    public function show(Region $region): Application|Factory|View
    {
        return view('regions.show', ['region' => $region]);
    }

    /**
     * @param int $id
     * @return Application|Factory|View
     */
    public function districts(int $id): Application|Factory|View
    {
        return view("districts.index", [
            'districts' => District::where(['region_id' => $id])->get()
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Region $region
     * @return Application|Factory|View
     */
    public function edit(Region $region): Application|Factory|View
    {
        return view('regions.edit', ['region' => $region]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param UpdateRegionRequest $request
     * @param Region $region
     * @return RedirectResponse
     */
    public function update(UpdateRegionRequest $request, Region $region): RedirectResponse
    {
        $region->update($request->validated());
        return Redirect::route('regions.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Region $region
     * @return RedirectResponse
     */
    public function destroy(Region $region): RedirectResponse
    {
        $region->delete();
        return Redirect::route('regions.index');
    }
}

resources/views/regions/create.blade.php
@extends('layouts.master')
@section('title')
    @lang('translation.create-region')
@endsection
@section('content')
    @component('components.breadcrumb')
        @slot('li_1')
            @lang('translation.region')
        @endslot
        @slot('title')
            @lang('translation.create-region')

        @endslot
    @endcomponent
    <form action="{{ route('regions.store') }}" method="post" autocomplete="off" class="needs-validation" validate>
        @csrf
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header">
                        @lang('translation.region')
                    </div>
                    <div class="card-body">
                        <div class="row gy-4">
                            <div class="mb-3 col-xxl-4 col-md-6">
                                <label class="form-label" for="order-number-input">
                                    @lang('translation.uz')
                                </label>
                                <input type="text"
                                       class="form-control text-uppercase @error('uz') is-invalid @enderror"
                                       name="uz" placeholder="@lang('translation.uz')"
                                       id="order-number-input" value="{{ old('uz') }}"
                                       tabindex="1">
                                @error('uz')
                                <span class="invalid-feedback" role="alert">
                                    <strong>@lang($message,['attribute'=>trans('translation.uz')])</strong>
                                </span>
                                @enderror
                            </div>
                            <div class="mb-3 col-xxl-4 col-md-6">
                                <label class="form-label" for="order-number-input">
                                    @lang('translation.ru')
                                </label>
                                <input type="text"
                                       class="form-control text-uppercase @error('ru') is-invalid @enderror"
                                       name="ru" placeholder="@lang('translation.ru')"
                                       id="order-number-input" value="{{ old('ru') }}"
                                       tabindex="2">
                                @error('ru')
                                <span class="invalid-feedback" role="alert">
                                    <strong>@lang($message,['attribute'=>trans('translation.ru')])</strong>
                                </span>
                                @enderror
                            </div>
                            <div class="mb-3 col-xxl-4 col-md-6">
                                <label class="form-label" for="order-number-input">
                                    @lang('translation.cr')
                                </label>
                                <input type="text"
                                       class="form-control text-uppercase @error('cr') is-invalid @enderror"
                                       name="cr" placeholder="@lang('translation.cr')"
                                       id="order-number-input" value="{{ old('cr') }}"
                                       tabindex="3">
                                @error('cr')
                                <span class="invalid-feedback" role="alert">
                                    <strong>@lang($message,['attribute'=>trans('translation.cr')])</strong>
                                </span>
                                @enderror
                            </div>
                        </div>
                        <div class="col-lg-4 col-sm-4 col-md-4">
                            <div class="text-start mb-3 btn-block">
                                <button type="submit" class="btn btn-success w-sm" name="save"
                                        tabindex="4"> @lang('translation.save') </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- end row -->
    </form>
@endsection

resources/views/regions/edit.blade.php
@extends('layouts.master')
@section('title')
    @lang('translation.edit-region')
@endsection
@section('content')
    @component('components.breadcrumb')
        @slot('li_1')
            @lang('translation.region')
        @endslot
        @slot('title')
            @lang('translation.edit-region')

        @endslot
    @endcomponent
    <form action="{{ route('regions.update',['region'=>$region->id]) }}" method="post" autocomplete="off"
          class="needs-validation" validate>
        @csrf
        @method('put')
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header">
                        @lang('translation.region')
                    </div>
                    <div class="card-body">
                        <div class="row gy-4">
                            <div class="mb-3 col-xxl-4 col-md-6">
                                <label class="form-label" for="order-number-input">
                                    @lang('translation.uz')
                                </label>
                                <input type="text"
                                       class="form-control text-uppercase @error('uz') is-invalid @enderror"
                                       name="uz" placeholder="@lang('translation.uz')"
                                       id="order-number-input" value="{{ $region->uz }}"
                                       tabindex="1">
                                @error('uz')
                                <span class="invalid-feedback" role="alert">
                                    <strong>@lang($message,['attribute'=>trans('translation.uz')])</strong>
                                </span>
                                @enderror
                            </div>
                            <div class="mb-3 col-xxl-4 col-md-6">
                                <label class="form-label" for="order-number-input">
                                    @lang('translation.ru')
                                </label>
                                <input type="text"
                                       class="form-control text-uppercase @error('ru') is-invalid @enderror"
                                       name="ru" placeholder="@lang('translation.ru')"
                                       id="order-number-input" value="{{ $region->ru }}"
                                       tabindex="2">
                                @error('ru')
                                <span class="invalid-feedback" role="alert">
                                    <strong>@lang($message,['attribute'=>trans('translation.ru')])</strong>
                                </span>
                                @enderror
                            </div>
                            <div class="mb-3 col-xxl-4 col-md-6">
                                <label class="form-label" for="order-number-input">
                                    @lang('translation.cr')
                                </label>
                                <input type="text"
                                       class="form-control text-uppercase @error('cr') is-invalid @enderror"
                                       name="cr" placeholder="@lang('translation.cr')"
                                       id="order-number-input" value="{{ $region->cr }}"
                                       tabindex="3">
                                @error('cr')
                                <span class="invalid-feedback" role="alert">
                                    <strong>@lang($message,['attribute'=>trans('translation.cr')])</strong>
                                </span>
                                @enderror
                            </div>
                        </div>
                        <div class="col-lg-4 col-sm-4 col-md-4">
                            <div class="text-start mb-3 btn-block">
                                <button type="submit" class="btn btn-success w-sm" name="save"
                                        tabindex="4"> @lang('translation.save') </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- end row -->
    </form>
@endsection

resources/views/regions/index.blade.php
@extends('layouts.master')
@section('title')
    @lang('translation.regions')
@endsection
@section('content')
    @component('components.breadcrumb')
        @slot('li_1')
            @lang('translation.pages')
        @endslot
        @slot('title')
            @lang('translation.regions')
        @endslot
    @endcomponent
    <div class="row">
        <div class="col-xl-12">
            <div class="card">
                <div class="card-header  border-1">
                    <div class="d-flex align-items-center">
                        <h5 class="card-title mb-0 flex-grow-1">@lang('translation.regions')</h5>
                        <div class="flex-shrink-0 ">
                            <a class="btn btn-ghost-primary bg-primary text-white"
                               href="{{ route('regions.create') }}">  @lang('translation.create-region') </a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <div class="table-responsive ">
                        <table class="table table-borderless table-hover align-middle table-nowrap mb-0">
                            <thead>
                            <tr>
                                <th scope="col">№</th>
                                <th scope="col">@lang('translation.uz')</th>
                                <th scope="col">@lang('translation.ru')</th>
                                <th scope="col">@lang('translation.cr')</th>
                                <th scope="col">@lang('translation.actions')</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach ($regions as $region)
                                <tr>
                                    <td class="fw-medium"> {{$loop->iteration}}</td>
                                    <td>
                                        <a href="{{ route('regions.districts',['id'=>$region->id]) }}">{{  $region->uz }}</a>
                                    </td>
                                    <td>
                                        <a href="{{ route('regions.districts',['id'=>$region->id]) }}">{{  $region->ru }}</a>
                                    </td>
                                    <td>
                                        <a href="{{ route('regions.districts',['id'=>$region->id]) }}">{{  $region->cr }}</a>
                                    </td>
                                    <td>
                                        <div class="hstack gap-3 fs-15">
                                            <a href="{{ route('regions.districts', ['id'=>$region->id]) }}"
                                               title="@lang("translation.view-information")" data-bs-toggle="tooltip"
                                               data-bs-placement="top"
                                               class="link-success">
                                                <i class="ri-eye-line align-middle"></i>
                                            </a>
                                            <a href="{{ route('regions.edit', ['region'=>$region->id]) }}"
                                               title="@lang("translation.edit-information")" data-bs-toggle="tooltip"
                                               data-bs-placement="top"
                                               class="link-warning">
                                                <i class="ri-pencil-line align-middle"></i>
                                            </a>
                                            @component('components.delete-btn')
                                                @slot('url')
                                                    {{ route('regions.destroy', ['region' => $region->id]) }}
                                                @endslot
                                            @endcomponent
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div><!-- end card-body -->
            </div><!-- end card -->
        </div><!-- end col -->
    </div>
@endsection
@section('script')
    <script src="{{ URL::asset('/assets/js/app.min.js') }}"></script>
@endsection