routes/web.php
<?php

use App\Http\Controllers\AutoController;
use App\Http\Controllers\BonusController;
use App\Http\Controllers\CertificateController;
use App\Http\Controllers\ConcernController;
use App\Http\Controllers\ConclusionController;
use App\Http\Controllers\DebitController;
use App\Http\Controllers\DillerController;
use App\Http\Controllers\DistrictController;
use App\Http\Controllers\EstateController;
use App\Http\Controllers\FileStoreController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\NotificationTemplateController;
use App\Http\Controllers\NotificationTypeController;
use App\Http\Controllers\OrderMembersController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\PurposeController;
use App\Http\Controllers\QrController;
use App\Http\Controllers\RegionController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\ToolsController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\UserInfoController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
//Language Translation
Route::get('index/{locale}', [HomeController::class, 'lang']);

Route::get('/', [HomeController::class, 'index'])->name('root');
Route::get('index', [HomeController::class, 'index'])->name('index');

//Update User Details
Route::post('/update-profile/{id}', [ProfileController::class, 'updateProfile'])->name('updateProfile');
Route::post('/update-password/{id}', [ProfileController::class, 'updatePassword'])->name('updatePassword');
Route::get('qr/show/{content}', [QrController::class, 'show'])->name('qr.show');
Route::get('qr/re-generate/{id}/{type}', [QrController::class, 'reGenerate'])->name('qr.generate');
Route::get('conclusion/test-water-mark', [ConclusionController::class, 'testWaterMark'])->name('wm.show');

Route::post('/member/remove', [OrderMembersController::class, 'remove'])->name('member.remove');
Route::post('/members/invite', [OrderMembersController::class, 'invite'])->name('members.invite');

Route::get('/estate', [EstateController::class, 'index'])->name('estate.index');
Route::get('/estate/create', [EstateController::class, 'create'])->name('estate.create');
Route::post('/estate/store', [EstateController::class, 'store'])->name('estate.store');
Route::get('/estate/edit/{id}', [EstateController::class, 'edit'])->name('estate.edit');
Route::put('/estate/update/{id}', [EstateController::class, 'update'])->name('estate.update');
Route::get('/estate/show/{order}', [EstateController::class, 'show'])->name('estate.show');
Route::get('/estate/show-activities/{order}', [EstateController::class, 'showActivities'])->name('estate.show-activities');
Route::get('/estate/show-team/{order}', [EstateController::class, 'showTeam'])->name('estate.show-team');
Route::get('/estate/show-documents/{order}', [EstateController::class, 'showDocuments'])->name('estate.show-documents');
Route::put('/estate/order-clone/{id}', [EstateController::class, 'orderClone'])->name('estate.clone');

Route::get('/auto', [AutoController::class, 'index'])->name('auto.index');
Route::get('/auto/create', [AutoController::class, 'create'])->name('auto.create');
Route::post('/auto/store', [AutoController::class, 'store'])->name('auto.store');
Route::get('/auto/edit/{id}', [AutoController::class, 'edit'])->name('auto.edit');
Route::put('/auto/update/{id}', [AutoController::class, 'update'])->name('auto.update');
Route::get('/auto/show/{order}', [AutoController::class, 'show'])->name('auto.show');
Route::get('/auto/show-activities/{order}', [AutoController::class, 'showActivities'])->name('auto.show-activities');
Route::get('/auto/show-team/{order}', [AutoController::class, 'showTeam'])->name('auto.show-team');
Route::get('/auto/show-documents/{order}', [AutoController::class, 'showDocuments'])->name('auto.show-documents');
Route::put('/auto/order-clone/{id}', [AutoController::class, 'orderClone'])->name('auto.clone');

Route::get('/conclusion/add/{id}/{type}', [ConclusionController::class, 'create'])->name('conclusion.add');
Route::post('/conclusion/store', [ConclusionController::class, 'store'])->name('conclusion.store');
Route::put('/conclusion/reject', [ConclusionController::class, 'reject'])->name('conclusion.reject');


Route::get('/tools', [ToolsController::class, 'index'])->name('tools.index');
Route::get('/user', [UserController::class, 'index'])->name('user.index');
Route::post('/user/store', [UserController::class, 'create'])->name('user.store');
Route::get('/user/show/{id}', [UserController::class, 'show'])->name('user.show');
Route::put('/user/update', [UserController::class, 'update'])->name('user.update');
Route::post('/user/favourite/{id}', [UserController::class, 'favourite'])->name('user.favourite');
Route::put('/user/password/change', [UserController::class, 'updatePassword'])->name('password.change');

Route::get('/user/info/edit', [UserInfoController::class, 'edit'])->name('profile.info.edit');
Route::put('/user/info/store', [UserInfoController::class, 'update'])->name('profile.info.update');

Route::get('/profile/edit', [UserController::class, 'edit'])->name('profile.edit');
Route::put('/profile/update', [UserController::class, 'update'])->name('profile.update');
Route::get('/profile/show-activities', [ProfileController::class, 'showActivities'])->name('profile.show-activities');
Route::get('/profile/show-projects', [ProfileController::class, 'showProjects'])->name('profile.show-projects');
Route::get('/profile/show-documents', [ProfileController::class, 'showDocuments'])->name('profile.show-documents');

Route::get('/user/profile', [ProfileController::class, 'profile'], 'profile')->name('profile');
Route::put('/user/activate/{id}', [UserController::class, 'activate'])->name('user.activate');
Route::put('/user/block/{id}', [UserController::class, 'block'])->name('user.block');
Route::get('/user/appraisers', [UserController::class, 'appraisers'])->name('user.appraisers');
Route::get('/appraisers/bonus', [UserController::class, 'appraisersBonus'])->name('appraisers.bonus');
Route::delete('/diller/{id}', [UserController::class, 'destroy'])->name('diller.destroy');

Route::get('/diller', DillerController::class)->name('diller.index');
Route::get('/role', [RoleController::class, 'index'])->name('role.index');
Route::put('/role/permit', [RoleController::class, 'permit'])->name('role.permit');
Route::get('/notification/type', NotificationTypeController::class)->name('notification.type.index');
Route::get('/notification/template', [NotificationTemplateController::class, 'index'])->name('notification.template.index');
//Route::post('/store/my/file', [FileStoreController::class, 'storeMyFile'])->name('store.my.file');
Route::post('/attach/file', [FileStoreController::class, 'attachFiles'])->name('attach.files');
Route::post('/attach/profile-file', [FileStoreController::class, 'attachProfileFiles'])->name('profile.files');
Route::get('/download/{file}', [FileStoreController::class, 'downloadFile'])->name('download');
Route::delete('file/delete/{file}', [FileStoreController::class, 'delete'])->name('file.delete');
Route::put('debit/credit', [BonusController::class, 'storeCredit'])->name('credit.store');
Route::resource('/debit', DebitController::class);
Route::resource('bonus', BonusController::class);
Route::resource('certificates', CertificateController::class);
Route::resource('purposes', PurposeController::class);
Route::resource('regions', RegionController::class);
Route::get('/regions/districts/{id}', [RegionController::class, 'districts'])->name('regions.districts');
Route::resource('districts', DistrictController::class);
Route::resource('concerns', ConcernController::class);

Route::get('{any}', [HomeController::class, 'pages'])->name('pages');

app/Models/Debit.php
<?php

namespace App\Models;

use App\Enums\OrderTypeEnum;
use App\Models\Traits\Filterable;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasOne;

/**
 * App\Models\Debit
 *
 * @property int $id
 * @property int $appraiser_id
 * @property int $order_id
 * @property int $cost
 * @property string $customer
 * @property string $expired
 * @property string $created_at
 * @property string $updated_at
 * @property string $status
 * @property-read \App\Models\User|null $appraiser
 * @property-read \App\Models\AutoOrder|null $order
 * @method static \Database\Factories\DebitFactory factory(...$parameters)
 * @method static \Illuminate\Database\Eloquent\Builder|Debit filter(\App\Http\FIlters\FilterInterface $filter)
 * @method static \Illuminate\Database\Eloquent\Builder|Debit newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Debit newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Debit query()
 * @method static \Illuminate\Database\Eloquent\Builder|Debit whereAppraiserId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Debit whereCost($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Debit whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Debit whereCustomer($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Debit whereExpired($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Debit whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Debit whereOrderId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Debit whereStatus($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Debit whereUpdatedAt($value)
 * @mixin \Eloquent
 * @property string|null $order_type
 * @method static \Illuminate\Database\Eloquent\Builder|Debit whereOrderType($value)
 */
class Debit extends Model
{
    use HasFactory, Filterable;

    public static string $NOPAID = "nopaid";
    public static string $PAID = "paid";

    /**
     * @var string[]
     */
    protected $fillable = [
        'appraiser_id',
        'order_id',
        'diller_id',
        'cost',
        'customer',
        'expired',
        'status',
        'order_type',
    ];

    public function appraiser(): HasOne
    {
        return $this->hasOne(User::class, 'id', 'appraiser_id');
    }

    public function diller(): HasOne
    {
        return $this->hasOne(User::class, 'id', 'appraiser_id');
    }

    public function order(): HasOne
    {
        if ($this->order_type == OrderTypeEnum::AUTO->name) {
            return $this->hasOne(AutoOrder::class, 'id', 'order_id');
        } else {
            return $this->hasOne(EstateOrder::class, 'id', 'order_id');
        }
    }

    public function getCreatedAtAttribute($value): string
    {
        return Carbon::parse($value)->format('d.m.Y');
    }

    public function getUpdatedAtAttribute($value): string
    {
        return Carbon::parse($value)->format('d.m.Y');
    }

    public function getExpiredAttribute($value): string
    {
        return Carbon::parse($value)->format('d.m.Y');
    }
}

app/Http/Controllers/DebitController.php
<?php

namespace App\Http\Controllers;

use App\Enums\RoleEnum;
use App\Http\Filters\DebitFilter;
use App\Http\Requests\DebitFilterRequest;
use App\Models\Debit;
use App\Models\User;
use Auth;
use Illuminate\Contracts\Container\BindingResolutionException;
use Illuminate\Http\RedirectResponse;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Redirect;
use Illuminate\View\View;

class DebitController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @param DebitFilterRequest $request
     * @return View
     * @throws BindingResolutionException
     */
    public function index(DebitFilterRequest $request): View
    {
        $data = $request->validated();
        if (Auth::user()->role == RoleEnum::DILLER->name) {
            $data['diller'] = Auth::id();
        }
        if (Auth::user()->role == RoleEnum::APPRAISER->name) {
            $data['appraiser'] = Auth::id();
        }
        $appraisers = User::where('role', RoleEnum::APPRAISER->name)->get();
        $filter = app()->make(DebitFilter::class, ['queryParams' => array_filter($data)]);
        Log::debug("Validated data {0}, Filter {1}", [$data, $filter]);

        $debits = Debit::filter($filter);
        return view('debit.index', [
            'debits' => $debits,
            'filters' => $request->all(),
            'appraisers' => $appraisers,
            'size' => $filter->getSize()
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param int $id
     * @return RedirectResponse
     */
    public function update(int $id): RedirectResponse
    {
        Debit::whereKey($id)
            ->update([
                'status' => Debit::$PAID
            ]);
        return Redirect::back();
    }
}

resources/views/debit/index.blade.php
@extends('layouts.master')
@section('title')
    @lang('translation.debit')
@endsection
@section('content')
    @component('components.breadcrumb')
        @slot('li_1')
            @lang('translation.pages')
        @endslot
        @slot('title')
            @lang('translation.debit')
        @endslot
    @endcomponent
    <div class="row">
        <div class="col-xl-12">
            <div class="card">
                <div class="card-body border border-dashed border-end-0 border-start-0">
                    <form autocomplete="false">
                        <div class="row g-3">
                            <form action="{{ route('debit.index') }}" method="get" autocomplete="off" novalidate>
                                <div class="col-xxl-4 col-sm-4">
                                    <div class="search-box">
                                        <input type="text" class="form-control search" name="search"
                                               value="{{ isset($filters['search']) ? $filters['search'] : '' }}"
                                               placeholder="@lang('translation.search-by-number-customer-owner')">
                                        <i class="ri-search-line search-icon"></i>
                                    </div>
                                </div>
                                <!--end col-->
                                <div class="col-xxl-2 col-sm-6">
                                    <div>
                                        <input type="text" class="form-control flatpickr-input"
                                               data-provider="flatpickr"
                                               name="period" value="{{ $filters['period'] ?? '' }}"
                                               data-date-format="d.m.Y"
                                               data-range-date="true" id="demo-datepicker"
                                               placeholder="@lang('translation.select-period')" readonly="readonly">
                                    </div>
                                </div>
                                <!--end col-->
                                <div class="col-xxl-2 col-sm-4">
                                    <div>
                                        <select data-choices data-choices-search-false onchange="this.form.submit()"
                                                data-choices-multiple-groups="false" class="form-control" name="status">
                                            <option value="" selected disabled>
                                                @lang('translation.select-status')</option>
                                            <option value="nopaid">
                                                @lang('translation.nopaid')
                                            </option>
                                            <option value="paid">
                                                @lang('translation.paid')
                                            </option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-xxl-2 col-sm-4">
                                    @if (Auth::user()->role != App\Enums\RoleEnum::DILLER->name)
                                        <div>
                                            <select data-choices data-choices-search-false
                                                    data-choices-multiple-groups="false" class="form-control"
                                                    name="appraiser" onchange="this.form.submit()">
                                                <option value="">@lang('translation.select-appraiser')</option>
                                                @foreach ($appraisers as $appraiser)
                                                    <option value="{{ $appraiser->id }}"
                                                        {{ isset($filters['appraiser']) && isset($filters['appraiser']) && $appraiser->name === $filters['appraiser'] ? 'selected' : '' }}>
                                                        {{ $appraiser->name }}
                                                    </option>
                                                @endforeach
                                            </select>
                                        </div>
                                    @endif
                                </div>
                                <!--end col-->

                                <div class="col-xxl-1 col-sm-2">
                                    @component('components.page-size',['size' => $size])@endcomponent
                                </div>
                                <!--end col-->
                                <div class="col-xxl-1 col-sm-2">
                                    <div>
                                        <button type="submit" class="btn btn-primary w-100">
                                            <i class="ri-equalizer-fill me-1 align-bottom"></i>
                                        </button>
                                    </div>
                                </div>
                                <!--end col-->
                            </form>
                        </div>
                        <!--end row-->
                    </form>
                </div>
                <div class="card-body">
                    <div class="live-preview">
                        <div class="table-responsive">
                            <table class="table table-borderless align-middle table-nowrap mb-0">
                                <thead>
                                <tr>
                                    <th scope="col">№</th>
                                    <th scope="col">@lang('translation.order-number')</th>
                                    <th scope="col">@lang('translation.customer')</th>
                                    <th scope="col">@lang('translation.cost')</th>
                                    <th scope="col">@lang('translation.created-date')</th>
                                    <th scope="col">@lang('translation.due-date')</th>
                                    <th scope="col">@lang('translation.appraiser')</th>
                                    <th scope="col">@lang('translation.status')</th>
                                    <th scope="col">@lang('translation.actions')</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach ($debits as $debit)
                                    <tr @if($debit->expired < date('d.m.Y',time()) && $debit->status=='nopaid') class="bg-danger" @endif>
                                        <td>

                                            {{ ($debits->currentPage() - 1) * $debits->perPage() + $loop->iteration }}
                                        </td>
                                        <td class="fw-medium">
                                            <a href="@if(\App\Enums\OrderTypeEnum::AUTO->name==$debit->order_type) {{route('auto.show', [$debit->order_id])}} @else {{route('estate.show', [$debit->order_id])}} @endif">
                                                {{ $debit->order->number }}
                                            </a>
                                        </td>
                                        <td>{{ $debit->customer }}</td>
                                        <td>
                                            @component('components.price', ['balance' => $debit->cost])
                                            @endcomponent
                                        </td>
                                        <td>{{ $debit->created_at }}</td>
                                        <td>{{ $debit->expired }}</td>
                                        <td>
                                            <a class="text-decoration-underline"
                                               href="{{ route('user.show',[$debit->appraiser->id]) }}">
                                                {{ $debit->appraiser->name }}
                                            </a>
                                        </td>
                                        <td>
                                            @if($debit->status=='paid')
                                                <span class="badge badge-gradient-warning">
                                                @lang('translation.paid')
                                            </span>
                                            @else
                                                <span class="badge badge-soft-success">
                                                @lang('translation.nopaid')
                                            </span>
                                            @endif
                                        </td>
                                        @if(in_array(Auth::user()->role,['admin',\App\Enums\RoleEnum::MANAGER->name]))
                                        <td>
                                            <div class="hstack gap-3 fs-15">
                                                <form method="post"
                                                      action="{{ route('debit.update', ['debit' => $debit->id]) }}">
                                                    @method('put')
                                                    @csrf
                                                    <button type="submit"
                                                            data-bs-toggle="tooltip"
                                                            data-bs-placement="bottom"
                                                            title="To'langan qilib belgilash"
                                                            class="btn btn-outline-warning btn-icon waves-effect waves-light">
                                                        <i class="ri-pencil-line"></i>
                                                    </button>
                                                </form>
                                            </div>
                                        </td>
                                        @endif
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                    {{ $debits->withQueryString()->links() }}

                </div><!-- end card-body -->
            </div><!-- end card -->
        </div><!-- end col -->
        @endsection
        @section('script')
            <script src="{{ URL::asset('assets/libs/prismjs/prismjs.min.js') }}"></script>

            <script src="{{ URL::asset('/assets/js/app.min.js') }}"></script>
@endsection